{-# OPTIONS --cubical #-}
module Everything where

open import Equiv
open import Container
open import Prelude
open import Relation.Unary
open import Relation.Binary.Equivalence.Reasoning
open import Relation.Binary.Construct.LowerBound
open import Relation.Nullary.Stable.Properties
open import Relation.Nullary.Stable.Base
open import Relation.Nullary.Discrete.Properties
open import Relation.Nullary.Discrete.Base
open import Relation.Nullary.Omniscience
open import Relation.Nullary.Decidable
open import Relation.Nullary.Discrete
open import Relation.Nullary.Stable
open import Relation.Nullary.Decidable.Properties
open import Relation.Nullary.Decidable.Logic
open import Relation.Nullary.Decidable.Base
open import Relation.Nullary
open import Relation.Binary
open import HLevels
open import Path
open import Function
open import Strict
open import Path.Reasoning
open import Function.Injective
open import Function.Biconditional
open import Function.Surjective.Properties
open import Function.Surjective.Base
open import Function.Isomorphism
open import Function.Fiber
open import Function.Injective.Properties
open import Function.Injective.Base
open import Function.Surjective
open import Algebra
open import Codata.Stream
open import Container.Membership
open import Container.Stream
open import Container.List.Isomorphism
open import Container.List.Syntax
open import Container.List
open import Level
open import Literals.Number
open import HITs.PropositionalTruncation.Sugar
open import HITs.PropositionalTruncation.Properties
open import HITs.PropositionalTruncation.Display
open import HITs.PropositionalTruncation
open import Data.Bool
open import Data.Unit.UniversePolymorphic
open import Data.Unit.Properties
open import Data.Fin.Properties
open import Data.Fin.Base
open import Data.Fin.Literals
open import Data.Empty.UniversePolymorphic
open import Data.Empty.Properties
open import Data.Empty.Base
open import Data.Empty
open import Data.Tuple.UniverseMonomorphic
open import Data.Tuple.Base
open import Data.Nat.Properties
open import Data.Nat.Base
open import Data.Nat.Literals
open import Data.Maybe.Properties
open import Data.Maybe.Sugar
open import Data.Maybe.Base
open import Data.Lift
open import Data.Product.NAry
open import Data.Sigma.Properties
open import Data.Sigma.Base
open import Data.Pi.Base
open import Data.List
open import Data.Vec.Inductive
open import Data.Vec.Iterated
open import Data.Maybe
open import Data.Sum.Properties
open import Data.List.Membership
open import Data.List.Relation.Unary
open import Data.List.Relation.Binary.Permutation
open import Data.List.Filter
open import Data.List.Properties
open import Data.List.Sugar
open import Data.List.Kleene.Membership
open import Data.List.Kleene.Relation.Unary
open import Data.List.Kleene
open import Data.List.Syntax
open import Data.List.Base
open import Data.List.Sort
open import Data.Sum
open import Data.Bool.Properties
open import Data.Fin
open import Data.Binary.Base
open import Data.Binary.Literals
open import Data.Pi
open import Data.Tuple
open import Data.Unit
open import Data.Nat
open import Data.Sigma
open import Data.Binary
open import Algebra.Construct.Dyck
open import Algebra.Construct.Free.Semilattice
open import Algebra.Construct.Free.Semilattice.Direct
open import Algebra.Construct.Free.Semilattice.Relation.Unary.Membership
open import Algebra.Construct.Free.Semilattice.Relation.Unary.All.Properties
open import Algebra.Construct.Free.Semilattice.Relation.Unary.All.Dec
open import Algebra.Construct.Free.Semilattice.Relation.Unary.All.Map
open import Algebra.Construct.Free.Semilattice.Relation.Unary.All.Def
open import Algebra.Construct.Free.Semilattice.Relation.Unary.Any.Properties
open import Algebra.Construct.Free.Semilattice.Relation.Unary.Any.Dec
open import Algebra.Construct.Free.Semilattice.Relation.Unary.Any.Map
open import Algebra.Construct.Free.Semilattice.Relation.Unary.Any.Def
open import Algebra.Construct.Free.Semilattice.Relation.Unary
open import Algebra.Construct.Free.Semilattice.FromList
open import Algebra.Construct.Free.Semilattice.Eliminators
open import Algebra.Construct.Free.Semilattice.Homomorphism
open import Algebra.Construct.Free.Semilattice.Extensionality
open import Algebra.Construct.Free.Semilattice.Union
open import Algebra.Construct.Free.Semilattice.Definition
open import Instance
