name: Compile Agda and Deploy HTML
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        cubical-ref: ["v0.8"]
        binary-ref: ["v0.2"]
        agda-ver: ["2.8.0"]

    steps:

    - name: Download Agda binary
      run: |
        set -e
        mkdir -p ~/.local/bin
        wget -qO- "https://github.com/agda/agda/releases/download/v${{ matrix.agda-ver }}/Agda-v${{ matrix.agda-ver }}-linux.tar.xz" | tar -xJ -C ~/.local/bin

    - name: Checkout main
      uses: actions/checkout@v4

    - name: Checkout cubical library
      uses: actions/checkout@v4
      with:
        repository: agda/cubical
        path: ~/cubical
        ref: ${{ matrix.cubical-ref }}

    - name: Checkout binary library
      uses: actions/checkout@v4
      with:
        repository: oisdk/agda-binary
        path: ~/agda-binary
        ref: ${{ matrix.binary-ref }}

    - name: Put cubical library in Agda library list
      run: |
        mkdir -p ~/.agda/
        touch ~/.agda/libraries
        echo "~/cubical/cubical.agda-lib" > ~/.agda/libraries
        echo "~/agda-binary/agda-binary.agda-lib" > ~/.agda/libraries

    - name: Compile agda library
      run: ./scripts/render.sh

    - name: Deploy html to github pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs
