name: Compile Agda and Deploy HTML
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        cubical-ref: ["v0.4"]
        agda-ref: ["v2.6.2.2"]

    steps:

    - uses: wenkokke/setup-agda@v2.0.0
      with:
        agda-version: ${{ matrix.agda-ver }}
        agda-libraries: |
          https://github.com/agda/cubical.git#${{ matrix.cubical-ref }}
          https://github.com/oisdk/agda-binary.git

    - name: Checkout main
      uses: actions/checkout@v3.4.0

    - name: Compile agda library
      run: ./scripts/render.sh

    - name: Deploy html to github pages
      if: steps.cache-agda.outputs.cache-hit != 'true'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs
